{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "\n",
    "os.chdir('../')\n",
    "sys.path.append(os.getcwd())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sqlalchemy import MetaData, create_engine\n",
    "\n",
    "db_url = \"postgresql://phish_ml_user:password@localhost:5432/phish_ml_db\"\n",
    "\n",
    "engine = create_engine(db_url)\n",
    "\n",
    "metadata = MetaData()\n",
    "metadata.reflect(engine)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "InvalidRequestError",
     "evalue": "When initializing mapper Mapper[Show(shows)], expression 'Track' failed to locate a name ('Track'). If this is a class name, consider adding this relationship() to the <class 'src.classes.show.Show'> class after both dependent classes have been defined.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/clsregistry.py:515\u001b[0m, in \u001b[0;36m_class_resolver._resolve_name\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    514\u001b[0m \u001b[39mif\u001b[39;00m rval \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m--> 515\u001b[0m     rval \u001b[39m=\u001b[39m d[token]\n\u001b[1;32m    516\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/util/_collections.py:345\u001b[0m, in \u001b[0;36mPopulateDict.__missing__\u001b[0;34m(self, key)\u001b[0m\n\u001b[1;32m    344\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m__missing__\u001b[39m(\u001b[39mself\u001b[39m, key: Any) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m Any:\n\u001b[0;32m--> 345\u001b[0m     \u001b[39mself\u001b[39m[key] \u001b[39m=\u001b[39m val \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mcreator(key)\n\u001b[1;32m    346\u001b[0m     \u001b[39mreturn\u001b[39;00m val\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/clsregistry.py:483\u001b[0m, in \u001b[0;36m_class_resolver._access_cls\u001b[0;34m(self, key)\u001b[0m\n\u001b[1;32m    481\u001b[0m             \u001b[39mreturn\u001b[39;00m value\n\u001b[0;32m--> 483\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mfallback[key]\n",
      "\u001b[0;31mKeyError\u001b[0m: 'Track'",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mInvalidRequestError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 7\u001b[0m\n\u001b[1;32m      4\u001b[0m Session \u001b[39m=\u001b[39m sessionmaker(bind\u001b[39m=\u001b[39mengine)\n\u001b[1;32m      5\u001b[0m session \u001b[39m=\u001b[39m Session()\n\u001b[0;32m----> 7\u001b[0m shows \u001b[39m=\u001b[39m session\u001b[39m.\u001b[39;49mquery(Show)\u001b[39m.\u001b[39mall()\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/session.py:2797\u001b[0m, in \u001b[0;36mSession.query\u001b[0;34m(self, *entities, **kwargs)\u001b[0m\n\u001b[1;32m   2777\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mquery\u001b[39m(\n\u001b[1;32m   2778\u001b[0m     \u001b[39mself\u001b[39m, \u001b[39m*\u001b[39mentities: _ColumnsClauseArgument[Any], \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs: Any\n\u001b[1;32m   2779\u001b[0m ) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m Query[Any]:\n\u001b[1;32m   2780\u001b[0m \u001b[39m    \u001b[39m\u001b[39m\"\"\"Return a new :class:`_query.Query` object corresponding to this\u001b[39;00m\n\u001b[1;32m   2781\u001b[0m \u001b[39m    :class:`_orm.Session`.\u001b[39;00m\n\u001b[1;32m   2782\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   2794\u001b[0m \n\u001b[1;32m   2795\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[0;32m-> 2797\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_query_cls(entities, \u001b[39mself\u001b[39;49m, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/query.py:273\u001b[0m, in \u001b[0;36mQuery.__init__\u001b[0;34m(self, entities, session)\u001b[0m\n\u001b[1;32m    267\u001b[0m \u001b[39m# session is usually present.  There's one case in subqueryloader\u001b[39;00m\n\u001b[1;32m    268\u001b[0m \u001b[39m# where it stores a Query without a Session and also there are tests\u001b[39;00m\n\u001b[1;32m    269\u001b[0m \u001b[39m# for the query(Entity).with_session(session) API which is likely in\u001b[39;00m\n\u001b[1;32m    270\u001b[0m \u001b[39m# some old recipes, however these are legacy as select() can now be\u001b[39;00m\n\u001b[1;32m    271\u001b[0m \u001b[39m# used.\u001b[39;00m\n\u001b[1;32m    272\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msession \u001b[39m=\u001b[39m session  \u001b[39m# type: ignore\u001b[39;00m\n\u001b[0;32m--> 273\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_set_entities(entities)\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/query.py:282\u001b[0m, in \u001b[0;36mQuery._set_entities\u001b[0;34m(self, entities)\u001b[0m\n\u001b[1;32m    279\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_set_entities\u001b[39m(\n\u001b[1;32m    280\u001b[0m     \u001b[39mself\u001b[39m, entities: Iterable[_ColumnsClauseArgument[Any]]\n\u001b[1;32m    281\u001b[0m ) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m--> 282\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_raw_columns \u001b[39m=\u001b[39m [\n\u001b[1;32m    283\u001b[0m         coercions\u001b[39m.\u001b[39;49mexpect(\n\u001b[1;32m    284\u001b[0m             roles\u001b[39m.\u001b[39;49mColumnsClauseRole,\n\u001b[1;32m    285\u001b[0m             ent,\n\u001b[1;32m    286\u001b[0m             apply_propagate_attrs\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m,\n\u001b[1;32m    287\u001b[0m             post_inspect\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[1;32m    288\u001b[0m         )\n\u001b[1;32m    289\u001b[0m         \u001b[39mfor\u001b[39;49;00m ent \u001b[39min\u001b[39;49;00m util\u001b[39m.\u001b[39;49mto_list(entities)\n\u001b[1;32m    290\u001b[0m     ]\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/query.py:283\u001b[0m, in \u001b[0;36m<listcomp>\u001b[0;34m(.0)\u001b[0m\n\u001b[1;32m    279\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_set_entities\u001b[39m(\n\u001b[1;32m    280\u001b[0m     \u001b[39mself\u001b[39m, entities: Iterable[_ColumnsClauseArgument[Any]]\n\u001b[1;32m    281\u001b[0m ) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m    282\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_raw_columns \u001b[39m=\u001b[39m [\n\u001b[0;32m--> 283\u001b[0m         coercions\u001b[39m.\u001b[39;49mexpect(\n\u001b[1;32m    284\u001b[0m             roles\u001b[39m.\u001b[39;49mColumnsClauseRole,\n\u001b[1;32m    285\u001b[0m             ent,\n\u001b[1;32m    286\u001b[0m             apply_propagate_attrs\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m,\n\u001b[1;32m    287\u001b[0m             post_inspect\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[1;32m    288\u001b[0m         )\n\u001b[1;32m    289\u001b[0m         \u001b[39mfor\u001b[39;00m ent \u001b[39min\u001b[39;00m util\u001b[39m.\u001b[39mto_list(entities)\n\u001b[1;32m    290\u001b[0m     ]\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/sql/coercions.py:406\u001b[0m, in \u001b[0;36mexpect\u001b[0;34m(role, element, apply_propagate_attrs, argname, post_inspect, **kw)\u001b[0m\n\u001b[1;32m    404\u001b[0m \u001b[39mif\u001b[39;00m insp \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m    405\u001b[0m     \u001b[39mif\u001b[39;00m post_inspect:\n\u001b[0;32m--> 406\u001b[0m         insp\u001b[39m.\u001b[39;49m_post_inspect\n\u001b[1;32m    407\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m    408\u001b[0m         resolved \u001b[39m=\u001b[39m insp\u001b[39m.\u001b[39m__clause_element__()\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py:1254\u001b[0m, in \u001b[0;36mHasMemoized.memoized_attribute.__get__\u001b[0;34m(self, obj, cls)\u001b[0m\n\u001b[1;32m   1252\u001b[0m \u001b[39mif\u001b[39;00m obj \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m   1253\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\n\u001b[0;32m-> 1254\u001b[0m obj\u001b[39m.\u001b[39m\u001b[39m__dict__\u001b[39m[\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m] \u001b[39m=\u001b[39m result \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mfget(obj)\n\u001b[1;32m   1255\u001b[0m obj\u001b[39m.\u001b[39m_memoized_keys \u001b[39m|\u001b[39m\u001b[39m=\u001b[39m {\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m}\n\u001b[1;32m   1256\u001b[0m \u001b[39mreturn\u001b[39;00m result\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py:2693\u001b[0m, in \u001b[0;36mMapper._post_inspect\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   2682\u001b[0m \u001b[39m@HasMemoized\u001b[39m\u001b[39m.\u001b[39mmemoized_attribute\n\u001b[1;32m   2683\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_post_inspect\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[1;32m   2684\u001b[0m \u001b[39m    \u001b[39m\u001b[39m\"\"\"This hook is invoked by attribute inspection.\u001b[39;00m\n\u001b[1;32m   2685\u001b[0m \n\u001b[1;32m   2686\u001b[0m \u001b[39m    E.g. when Query calls:\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   2691\u001b[0m \n\u001b[1;32m   2692\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[0;32m-> 2693\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_check_configure()\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py:2374\u001b[0m, in \u001b[0;36mMapper._check_configure\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   2366\u001b[0m \u001b[39m@util\u001b[39m\u001b[39m.\u001b[39mlanghelpers\u001b[39m.\u001b[39mtag_method_for_warnings(\n\u001b[1;32m   2367\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mThis warning originated from the `configure_mappers()` process, \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m   2368\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mwhich was invoked automatically in response to a user-initiated \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   2371\u001b[0m )\n\u001b[1;32m   2372\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_check_configure\u001b[39m(\u001b[39mself\u001b[39m) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m   2373\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mregistry\u001b[39m.\u001b[39m_new_mappers:\n\u001b[0;32m-> 2374\u001b[0m         _configure_registries({\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mregistry}, cascade\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m)\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py:4186\u001b[0m, in \u001b[0;36m_configure_registries\u001b[0;34m(registries, cascade)\u001b[0m\n\u001b[1;32m   4180\u001b[0m     Mapper\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39m_for_class(Mapper)\u001b[39m.\u001b[39mbefore_configured()  \u001b[39m# type: ignore # noqa: E501\u001b[39;00m\n\u001b[1;32m   4181\u001b[0m     \u001b[39m# initialize properties on all mappers\u001b[39;00m\n\u001b[1;32m   4182\u001b[0m     \u001b[39m# note that _mapper_registry is unordered, which\u001b[39;00m\n\u001b[1;32m   4183\u001b[0m     \u001b[39m# may randomly conceal/reveal issues related to\u001b[39;00m\n\u001b[1;32m   4184\u001b[0m     \u001b[39m# the order of mapper compilation\u001b[39;00m\n\u001b[0;32m-> 4186\u001b[0m     _do_configure_registries(registries, cascade)\n\u001b[1;32m   4187\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m   4188\u001b[0m     _already_compiling \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py:4228\u001b[0m, in \u001b[0;36m_do_configure_registries\u001b[0;34m(registries, cascade)\u001b[0m\n\u001b[1;32m   4226\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m mapper\u001b[39m.\u001b[39mconfigured:\n\u001b[1;32m   4227\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m-> 4228\u001b[0m         mapper\u001b[39m.\u001b[39;49m_post_configure_properties()\n\u001b[1;32m   4229\u001b[0m         mapper\u001b[39m.\u001b[39m_expire_memoizations()\n\u001b[1;32m   4230\u001b[0m         mapper\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mmapper_configured(mapper, mapper\u001b[39m.\u001b[39mclass_)\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py:2391\u001b[0m, in \u001b[0;36mMapper._post_configure_properties\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   2388\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_log(\u001b[39m\"\u001b[39m\u001b[39minitialize prop \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m, key)\n\u001b[1;32m   2390\u001b[0m \u001b[39mif\u001b[39;00m prop\u001b[39m.\u001b[39mparent \u001b[39mis\u001b[39;00m \u001b[39mself\u001b[39m \u001b[39mand\u001b[39;00m \u001b[39mnot\u001b[39;00m prop\u001b[39m.\u001b[39m_configure_started:\n\u001b[0;32m-> 2391\u001b[0m     prop\u001b[39m.\u001b[39;49minit()\n\u001b[1;32m   2393\u001b[0m \u001b[39mif\u001b[39;00m prop\u001b[39m.\u001b[39m_configure_finished:\n\u001b[1;32m   2394\u001b[0m     prop\u001b[39m.\u001b[39mpost_instrument_class(\u001b[39mself\u001b[39m)\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/interfaces.py:544\u001b[0m, in \u001b[0;36mMapperProperty.init\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    537\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"Called after all mappers are created to assemble\u001b[39;00m\n\u001b[1;32m    538\u001b[0m \u001b[39mrelationships between mappers and perform other post-mapper-creation\u001b[39;00m\n\u001b[1;32m    539\u001b[0m \u001b[39minitialization steps.\u001b[39;00m\n\u001b[1;32m    540\u001b[0m \n\u001b[1;32m    541\u001b[0m \n\u001b[1;32m    542\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m    543\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_configure_started \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[0;32m--> 544\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdo_init()\n\u001b[1;32m    545\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_configure_finished \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/relationships.py:1632\u001b[0m, in \u001b[0;36mRelationshipProperty.do_init\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1630\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_check_conflicts()\n\u001b[1;32m   1631\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_process_dependent_arguments()\n\u001b[0;32m-> 1632\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_setup_entity()\n\u001b[1;32m   1633\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_setup_registry_dependencies()\n\u001b[1;32m   1634\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_setup_join_conditions()\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/relationships.py:1851\u001b[0m, in \u001b[0;36mRelationshipProperty._setup_entity\u001b[0;34m(self, _RelationshipProperty__argument)\u001b[0m\n\u001b[1;32m   1844\u001b[0m resolved_argument: _ExternalEntityType[Any]\n\u001b[1;32m   1846\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(argument, \u001b[39mstr\u001b[39m):\n\u001b[1;32m   1847\u001b[0m     \u001b[39m# we might want to cleanup clsregistry API to make this\u001b[39;00m\n\u001b[1;32m   1848\u001b[0m     \u001b[39m# more straightforward\u001b[39;00m\n\u001b[1;32m   1849\u001b[0m     resolved_argument \u001b[39m=\u001b[39m cast(\n\u001b[1;32m   1850\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39m_ExternalEntityType[Any]\u001b[39m\u001b[39m\"\u001b[39m,\n\u001b[0;32m-> 1851\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_clsregistry_resolve_name(argument)(),\n\u001b[1;32m   1852\u001b[0m     )\n\u001b[1;32m   1853\u001b[0m \u001b[39melif\u001b[39;00m callable(argument) \u001b[39mand\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39misinstance\u001b[39m(\n\u001b[1;32m   1854\u001b[0m     argument, (\u001b[39mtype\u001b[39m, mapperlib\u001b[39m.\u001b[39mMapper)\n\u001b[1;32m   1855\u001b[0m ):\n\u001b[1;32m   1856\u001b[0m     resolved_argument \u001b[39m=\u001b[39m argument()\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/clsregistry.py:519\u001b[0m, in \u001b[0;36m_class_resolver._resolve_name\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    517\u001b[0m             rval \u001b[39m=\u001b[39m \u001b[39mgetattr\u001b[39m(rval, token)\n\u001b[1;32m    518\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mKeyError\u001b[39;00m \u001b[39mas\u001b[39;00m err:\n\u001b[0;32m--> 519\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_raise_for_name(name, err)\n\u001b[1;32m    520\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mNameError\u001b[39;00m \u001b[39mas\u001b[39;00m n:\n\u001b[1;32m    521\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_raise_for_name(n\u001b[39m.\u001b[39margs[\u001b[39m0\u001b[39m], n)\n",
      "File \u001b[0;32m~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sqlalchemy/orm/clsregistry.py:500\u001b[0m, in \u001b[0;36m_class_resolver._raise_for_name\u001b[0;34m(self, name, err)\u001b[0m\n\u001b[1;32m    490\u001b[0m     \u001b[39mraise\u001b[39;00m exc\u001b[39m.\u001b[39mInvalidRequestError(\n\u001b[1;32m    491\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mWhen initializing mapper \u001b[39m\u001b[39m{\u001b[39;00m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mprop\u001b[39m.\u001b[39mparent\u001b[39m}\u001b[39;00m\u001b[39m, \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    492\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m'\u001b[39m\u001b[39mexpression \u001b[39m\u001b[39m\"\u001b[39m\u001b[39mrelationship(\u001b[39m\u001b[39m{\u001b[39;00m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39marg\u001b[39m!r}\u001b[39;00m\u001b[39m)\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m seems to be \u001b[39m\u001b[39m'\u001b[39m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    497\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m[\u001b[39m\u001b[39m'\u001b[39m\u001b[39m{\u001b[39;00mclsarg\u001b[39m}\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m]] = relationship()\u001b[39m\u001b[39m\\\"\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    498\u001b[0m     ) \u001b[39mfrom\u001b[39;00m \u001b[39merr\u001b[39;00m\n\u001b[1;32m    499\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m--> 500\u001b[0m     \u001b[39mraise\u001b[39;00m exc\u001b[39m.\u001b[39mInvalidRequestError(\n\u001b[1;32m    501\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mWhen initializing mapper \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m, expression \u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m failed to \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    502\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mlocate a name (\u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m). If this is a class name, consider \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    503\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39madding this relationship() to the \u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m class after \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    504\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mboth dependent classes have been defined.\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    505\u001b[0m         \u001b[39m%\u001b[39m (\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mprop\u001b[39m.\u001b[39mparent, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39marg, name, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mcls)\n\u001b[1;32m    506\u001b[0m     ) \u001b[39mfrom\u001b[39;00m \u001b[39merr\u001b[39;00m\n",
      "\u001b[0;31mInvalidRequestError\u001b[0m: When initializing mapper Mapper[Show(shows)], expression 'Track' failed to locate a name ('Track'). If this is a class name, consider adding this relationship() to the <class 'src.classes.show.Show'> class after both dependent classes have been defined."
     ]
    }
   ],
   "source": [
    "from src.classes import Show, Tour, Venue, Track\n",
    "from sqlalchemy.orm import sessionmaker\n",
    "\n",
    "Session = sessionmaker(bind=engine)\n",
    "session = Session()\n",
    "\n",
    "shows = session.query(Show).all()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'Show' object has no attribute 'tracks'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 4\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39m# print the last show, sorted by date\u001b[39;00m\n\u001b[1;32m      2\u001b[0m last_show \u001b[39m=\u001b[39m session\u001b[39m.\u001b[39mquery(Show)\u001b[39m.\u001b[39morder_by(Show\u001b[39m.\u001b[39mdate\u001b[39m.\u001b[39mdesc())\u001b[39m.\u001b[39mfirst()\n\u001b[0;32m----> 4\u001b[0m last_show\u001b[39m.\u001b[39;49mtracks\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'Show' object has no attribute 'tracks'"
     ]
    }
   ],
   "source": [
    "# print the last show, sorted by date\n",
    "last_show = session.query(Show).order_by(Show.date.desc()).first()\n",
    "\n",
    "last_show.tracks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.2"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "b50ee7714ba4d894d2bea08ee2ae7549dc6b7012de04df509e31f82378202b59"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
